fixed 374a88034166ff3495893ed68eda5cedac9b9b19
cause error with
/home/susi/susi_server/src/ai/susi/server/api/cms/DeleteSkillService.java:82:
error: method pushCommit in class DAO cannot be applied to given types;
                DAO.pushCommit(git, "Deleted " + skill_name);
                   ^
  required: Git,String,String
  found: Git,String
  reason: actual and formal argument lists differ in length