Fixed !! (#1444)
* removed bad where phrases

* fix uncaught exception on empty response (#1245)

loading data from a remote API uses HttpClient.load, which might throw
an IOException "no content available for url " + source_url

2019-03-17 11:01:54.353 WARN root  - SusiInference.applyProcedures
java.io.IOException: no content available for url https://api.wolframalpha.com/v2/query?input=describe+4+time+9&output=JSON&appid=9WA6XR-26EWTGEVTE
	at ai.susi.tools.HttpClient.load(HttpClient.java:536)
	at ai.susi.server.api.susi.ConsoleService.loadData(ConsoleService.java:106)
	at ai.susi.mind.SusiInference.applyProcedures(SusiInference.java:296)
	at ai.susi.mind.SusiIntent.consideration(SusiIntent.java:788)
	at ai.susi.mind.SusiMind.react(SusiMind.java:460)
	at ai.susi.mind.SusiMind.reactMinds(SusiMind.java:514)
	at ai.susi.mind.SusiCognition.<init>(SusiCognition.java:119)
	at ai.susi.server.api.susi.SusiService.serviceImpl(SusiService.java:263)
	at ai.susi.server.api.susi.SusiService.serviceImpl(SusiService.java:75)
	at ai.susi.server.AbstractAPIHandler.process(AbstractAPIHandler.java:138)
	at ai.susi.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:78)

This exception is nowhere caught.
One possible place would be ConsoleService.loadData, but since the
return value of this function is expected to already contain a certain
json format response, returning an empty response or "{}" here does not
work.
The next level SusiInference.applyProcedure. Add a try/catch there
and log that no answer was received.

* new Dockerfile and README on building/running (#1243)

* new Dockerfile and README on building/running

* add URLs

* add skill_repo.enable configuration variable disabling git access (#1244)

* fix draft dir creation (#1246)

* add systemd service file and install into release tarball (#1251)

* add a systemd service file and put it into release tarball

* add another unit file for systemd user

* fixed concurrency problem in log appender

* don't do pull/push on the skill repo

* systemd unit file changes

add User=@SUSI_SERVER_USER@ to ss-susi-server.service.in

remove the @ variant of the service file since we do not
support multi-user setups at the moment

* allow for logging to stdout while still daemonizing (#1254)

In the systemd service unit we want the daemon be of type
forking, so that systemd can reliable determine whether startup
has completed.

We add a setting SS_LOG_TO_STDOUT (cmd line option -o) to start.sh
that triggers this.

For the systemd unit we set the above env variable to 1, set
the type to forking, and in addition specify for stability the
location of the PID file.

* Fix image placeholder (#1258)

* fix for SUPERADMIN rights

* added another susi dream reader for local etherpads
which may listen at http://localhost:9001
That etherpad-lite must have it's home path at
~/SUSI.AI/etherpad-lite/
and the dream pad must have the name "susi".
This dream is always read, no dreaming mode is required.

* added activation, skill and storage for user-defined front-end language

* open browser window only on mac oder windows

* fixed stop command

* added system configuration local.openBrowser.enable

* Update changeUserSettings to accept various paramters (#1261)

* non-fix for https://github.com/fossasia/susi_server/issues/1262
The bug is actually no bug because the sample skill is wrong:
an empty line is missing between the intents.
But the fix is required for empty thoughts.

* Add missing keys in changeUserSettings #1263

* Compress image before storing in upload avatar image (#1259)

* Fixes #1269: CHange verify email domain from accounts to susi.ai

* add music shuffle intent (#1271)

* update the gradle wrapper (#1273)

* Fix compress image upload #1275 (#1276)

* activate next and previous actions, add skills

* Update apiKeys.json to allow admin to update keys (#1266)

* added comments and asserts for language debugging

* added language attribute in action

* Add 'Reported Skills' servlet for Admin section #1268 (#1274)

* added soundcloud scraper

* enhanced logging in console services

* fixed "unmappable character for encoding ASCII" during compile time

* patched a test case (strange)

* preload pointed to the wrong jar file

* added soundclound action

* fixed soundcloud audio_play verification

* Update GetReportSkillServer Servlet #1281

* Fix Add apiKey service gives error #1283

* reduced complexity of skill parser

* reverted classpath changes

* enhances abstraction of SusiSkillFile

* fixed release script

* added application plugin to gradle build to enable gradle distTar

* fixed processing of short term memory
and added stub for long term memory storage
also included: skill fixes

* norberts recommendations are the best recommendations

* woa

* Implement SkillSlideshow Servlet #1293

* Enhance Search Functionality in getSkillList #1291 (#1292)

* Fix search using example #1301

* Enhance SkillsMetricsDataService endpoint to return system skills (#1304)

* fixed https://github.com/fossasia/susi_server/issues/1287

* JSON library update

* fix for skill parser

* generalized inference generation

* refactoring in intent parser

* Fix multi search using search type #1305 (#1307)

* refactoring answer computation

* introduced queueing flow - to be used for timed actions / stub

* Implement Service to Configure Mail Settings #1296 (#1296)

* fixed test path

* queue -> plan

* another planning example

* regex fix for QUEUE flow command
and testing code

* implemented timed planning

* further fixing planning

* Add Skill filter in SkillListService #1309 (#1310)

* Add smtp get configure in Email Settings Service #1313 (#1314)

* refactoring and fixing of planned actions
also: removed side-effects

* library upgrade

* Add server side validation (#1312)

* Add ListPrivateSkillService

* added ability to parse more date formats

* fixed out-ouf-file-handle problem

* added intelligent nested reflection call matching

* Add ListDeviceService (#1322)

* Fix password RegEx #1323 (#1324)

* Add Data over time for charts in ListSkillService #1317 (#1318)

* Fixes #1325: Make API to return list of devices (#1326)

* Fix rating over time date formats #1328

* Make ListPrivateSkillService to return array list (#1330)

* Fix Skill Date Over time returning empty #1331

* Get Wolfram Alpha key from apiKeys instead of hardcoded config (#1321)

* Get Wolfram Alpha key from apiKeys instead of hardcoded config properties #1320

* Fix 101

* Add server side validation for SignUp user #1334

* Modify DeleteSkillService so it can be deleted by an admin

* Fix getUsers to return UserStats

* Modify RemoveUserDevice and DeleteSkillService (#1338)

* Modify GetUsers to return signupTime and lastLoginTime

* Add more metadata to reportedskills #1347

* Modify getUsers to return device Stats and fix user stats

* Fix SkillsToBeDeleted #1353

* Add support for storing API keys at user level #1286

* "set an alam"

* Modify GetSkillJsonService and ModifySkillService

* feat: Enhance password pattern type (#1357)

* Add ListPrivateDraftSkillService endpoint (#1362)

* Fix User Level API #1363

* Fix forgot password reset link #1366 (#1367)

* better testing of mind

* Modify ListDeviceService to return lastActive and lastLoginIP

* Fix key on no user level API #1369 (#1370)

* fixed memory exponential growth in case of repeated flow commands

* fix for getUserStats=true

* accept any kind of time format for planned actions

* fixed https://github.com/fossasia/susi_server/issues/1375

* Add functionality to disable/enable captcha #1373 (#1374)

* fix for signup time creation and monitoring

* fixed https://github.com/fossasia/susi_server/issues/1376

* Allow Admin to update User settings (#1380)

* fix for https://github.com/fossasia/susi_server/issues/1382

* fixed signupTime date format

* Allow Admins to change profile picture of User (#1383)

* Allow admin to fetch user image

* Fix date for devices over time

* added abilities to use word tokens for further abstraction
also fixed skill ranking

* fix for token key computation

* Add functionality to disable/enable captcha  #1373 (#1389)

* quickfix for date parsing problem

* another quickfix

* better rules for default image in case no one exists

* fix for missing language declaration using susi dreams

* added some NLU hacks

* helper to debug exceptions

* added reflection to console rules
did also some generalization in susi argument evaluation

* fixed reflection in urls

* fixed https://github.com/fossasia/susi_server/issues/1393

* implemented reflection evaluation inside javascript bang code

* allow CORS

* Add speechPitch to possible settings value

* added 'Accept: application/json' http header to requests to json endpoints

* added custom http request headers, the ability to omit a path and the ability to use the response header as data input

* added ability to overwrite setting with system properties

* fixed double occurrences of answers.
Cause was a complex reaction of in-depth reflection combination which
occurred only for sabta answers. These answers should not be considered
as valid in reflection computation.

* fix for parser bug

* Css changes (#1403)

* debugging code + longer time-out for client requests
the request to wolfram alpha went into a time-out when the
time-out was set to 3000 milliseconds

* better debugging

* Thread naming for better debugging

* increase turnaround time indevelopment

* fix in label computation

* added line numbers to skill model
this enhances debugging as it is now much easier to find out where
skills are generated from

* added -Xverify:none to increase startup speed

* Using skill_source instead of "skill" as attribute for skill sources.

This supports an additional assignment of "skill_line" (tbd)

* more handling of line numbers for skills

* more NLU

this works, you can ask i.e. "susi can you tell me who is pewdipie
please". This deconstructs into the core question "who is pewdipie" and
is resolved. However, it creates another duplicate answer bug which must
be investigated further

* fixed several bugs (concurrency, cloning, empty expressions, double
answers)

however, double answers still appear when doing reflections.

* fix for wolframalpha key retrieval

* as I could not find the real reason for double answers, I add this very
bad patch. It should be removed as soon as we find the cause.

* one part of the location skill is not working any more, deleted it.

It should produce a map anyway

* added ability to read the host name of the server which is hosting susi

* introduced a debug mode

(does not conflict with current clients! - if they are correctly made)

* keeping the data object because clients depend on it.

However this should be changed

* Update alarm.txt

* added the disabled line to disable the local etherpad dream

* fix for npe

* metadata is used by the linux device

* Delete robots.txt

* removed bluemix

* Update app.json

* mv systemd directory to system-integration/systemd, update release script

* add susi server desktop file

* fix release packaging of system integration stuff

* Update README.rst (#1420)

* applying urlencoding in url reflection

* clean submodule

* deleted public-transport-enabler in favor of https://marudor.de/

* removed Bahn Console Service

* removed submodule from documentation

* performance enhancements

* removed remaining parts of public-transport-enabler

* cleanup of skill transactions

* added log initialization error self-healing

* added memory log and more efficient matcher during initialization

* enhancements in skill parsing (speed and memory footprint)

* slightly more default memory

* added missing class

* reduced size of cache

* lazy initialization for JsonFile

* catch OOM and continue during initialization

* setting proper utf-8 encoding as default for javac in gradle

* fix for missing library

* adding lazy initialization for volatile objects in JsonTray

* giving up lazy initialization to prevent oom during operation

* deal with left-over pid files despite dead process

* initialize tray objects first to reduce risk that they cannot
initialized due to not enough memory

* case for non-existing files - they will be created

* add README.rst explanation about deployment branches

* changed workflow of intent scoring
pattern computation is now reduced
This also prepares data structures to use less memory

* added missing class for last commit

* attempt to save memory for utterances

* enhanced SusiPattern computation

* Create a script to auto deploy in hcloud

* pass -Id to start.sh in .desktop ans systemd file

* add relocatable start/stop wrapper scripts

* update release.sh to install everything from system-integration/

* fix shell code

* we should **wait** for susi-server to be finished starting up!

* adjust desktop file to susi-config install desktop file

* switch to SUSIDIR in systemd service file

* rename start/stop scripts and desktop files

* use susi-server {start|stop} instead of susi-server-{start,stop}

Co-authored-by: Michael Christen <Orbiter@users.noreply.github.com>
Co-authored-by: Norbert Preining <norbert@preining.info>
Co-authored-by: Shubham Gupta <shubhamg@outlook.com>
Co-authored-by: Harsh Jindal <31013104+harsh-jindal@users.noreply.github.com>
Co-authored-by: Akshat Garg <akshatnitd@gmail.com>
Co-authored-by: Alok Kumar <alok760@gmail.com>
Co-authored-by: Amartya Mondal <atm1504.in@gmail.com>
Co-authored-by: Savin Abeysooriya <31475940+savinabeysooriya@users.noreply.github.com>
Co-authored-by: Mario Behling <mb@mariobehling.de>
Co-authored-by: Kumuditha Udayanga Karunarathna <kumudithaudaya@gmail.com>